### ISSUE TITLE
Error while Modifying Order Grid with Email Address Column

### ISSUE THREAD

**Issue by JOlivos00** [husseycoding/customordergrid#10] opened 2016-10-11 02:14 UTC
We are using the Custom Order Grid module for Magento. I added the email as a column however when I tried to filter orders by typing in an email address in the Order view, I got the following error. Now every time email is selected as a column, I get the same error and can't see the order page unless I remove the email column.

There has been an error processing your request
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'main_table.customer_email' in 'where clause'
Trace:
#0 /chroot/home/butterfi/test.butterfieldmarket.com/html/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /chroot/home/butterfi/test.butterfieldmarket.com/html/lib/Zend/Db/Statement.php(300): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /chroot/home/butterfi/test.butterfieldmarket.com/html/lib/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#3 /chroot/home/butterfi/test.butterfieldmarket.com/html/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT COUNT(*)...', Array)
#4 /chroot/home/butterfi/test.butterfieldmarket.com/html/lib/Varien/Db/Adapter/Pdo/Mysql.php(389): Zend_Db_Adapter_Pdo_Abstract->query('SELECT COUNT(*)...', Array)
#5 /chroot/home/butterfi/test.butterfieldmarket.com/html/lib/Zend/Db/Adapter/Abstract.php(825): Varien_Db_Adapter_Pdo_Mysql->query(Object(Varien_Db_Select), Array)
#6 /chroot/home/butterfi/test.butterfieldmarket.com/html/lib/Varien/Data/Collection/Db.php(217): Zend_Db_Adapter_Abstract->fetchOne(Object(Varien_Db_Select), Array)
#7 /chroot/home/butterfi/test.butterfieldmarket.com/html/lib/Varien/Data/Collection.php(225): Varien_Data_Collection_Db->getSize()
#8 /chroot/home/butterfi/test.butterfieldmarket.com/html/lib/Varien/Data/Collection.php(211): Varien_Data_Collection->getLastPageNumber()
#9 /chroot/home/butterfi/test.butterfieldmarket.com/html/lib/Varien/Data/Collection/Db.php(476): Varien_Data_Collection->getCurPage()

**Comment by husseycoding** [comment] 2016-10-11 06:23
Are you using any other extensions in conjunction with custom order grid which affect the order grid page?  Has custom order grid been modified in any way?  If you clear your cookies to give yourself a new session you will be able to view the grid again with email column added.

**Comment by husseycoding** [comment] 2016-10-26 04:56
Not enough information, closing.  With just custom order grid running filtering the sorting has been tested across all columns without error.  Likely caused by addition of extra module adding similar functionality.

**Closed as completed by husseycoding** 2016-10-26 04:56 UTC
